services:
  openvps-client:
    image: dperson/openvpn-client
    container_name: openvps-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun    
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp      
    environment:
      - PUID=568
      - PGID=568
      - DEFAULT_GATEWAY="false"
      - DNS="true"
    volumes:
      - E:\Users\Mark\Source\GitHub\openvpn-client\.config:/vpn
    healthcheck:
      test: curl --fail ifconfig.me || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s  
    restart: unless-stopped    
  curl-test:
    image: curlimages/curl:latest
    network_mode: "service:openvps-client"
    command: curl ifconfig.me
    depends_on:
      openvps-client:
        condition: service_healthy          
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: "service:openvps-client"
    depends_on:
      openvps-client:
        condition: service_healthy            
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - E:\Temp\Docker\Config:/config
      - E:\Temp\Docker\Downloads:/downloads #optional
    restart: unless-stopped
